### ISSUE TITLE
ModuleNotFoundError: No module named 'models.alexnet'

### ISSUE THREAD

**Issue by hugddygff** [microsoft/robustdg#15]
can you share the codes of alexnet

**Comment by divyat09** [comment]
Thanks for pointing this, the code in the master has not been updated. The current code is in the mia_adv_attacks branch: https://github.com/microsoft/robustdg/blob/mia_adv_attacks/models/alexnet.py 

I will integrate the mia_adv_attacks branch with the master by this week and update you here. Else you may use the code from the mia_adv_attacks branch for now.

**Comment by divyat09** [comment]
Thanks for pointing this, the code in the master has not been updated. The current code is in the mia_adv_attacks branch: https://github.com/microsoft/robustdg/blob/mia_adv_attacks/models/alexnet.py

I will integrate the mia_adv_attacks branch with the master by this week and update you here. Else you may use the code from the mia_adv_attacks branch for now.

**Comment by hugddygff** [comment]
> Thanks for pointing this, the code in the master has not been updated. The current code is in the mia_adv_attacks branch: https://github.com/microsoft/robustdg/blob/mia_adv_attacks/models/alexnet.py
> 
> I will integrate the mia_adv_attacks branch with the master by this week and update you here. Else you may use the code from the mia_adv_attacks branch for now.

Thanks very much

**Comment by divyat09** [comment]
The branch mia_adv_attacks has been merged with the master branch. You can find the alexnet module in the master now. Also, you may refer to this updated notebook for reproducing the results of the paper.

Closing this issue.
