### ISSUE TITLE
Dataloader for PACS and VLCS

### ISSUE THREAD

**Issue by ChongZhangZC** [microsoft/robustdg#2]
Could you release the dataloader of other datasets such as PACS or VLCS?
Thank you!

**Comment by divyat09** [comment]
Hi, sure we plan to release data loaders for both of them pretty soon.

**Comment by ChongZhangZC** [comment]
Excellent! Looking forward to the update!

**Comment by ChongZhangZC** [comment]
> Hi, sure we plan to release data loaders for both of them pretty soon.

Excellent! Looking forward to the update!

**Comment by divyat09** [comment]
Hi, the PACS data loader has been merged with the master branch, you check the data loader in the directory; 
'data/pacs/'

Example command to run ERM on the dataset PACS with the test domain as Photo:

python train.py --dataset pacs --method_name erm_match --match_case 0.01 --penalty_ws 0.0 --train_domains art_painting cartoon sketch --test_domains photo --out_classes 7 --perfect_match 0 --img_c 3  --pre_trained 1
