### ISSUE TITLE
Cannot reproduce results following docs/notebooks/robustdg_getting_started.ipynb

### ISSUE THREAD

**Issue by Ardor-Wu** [microsoft/robustdg#20]
I have followed instruction from docs/notebooks/robustdg_getting_started.ipynb, but I encountered CUDA out of memory, so I have halved the batch size from 256 to 128. The accuracy is slightly lower than 96.1, like 95.575 or 96.02. That is OK, but my T-SNE Plots are very bad (attached) compared to the given figure. My MIA accuracy is much higher than that on the notebook, typically 65-70, and matchdg has slightly higher MIA accuracy. It is also strange that I ran out of memory with 16 GB memory.
![image](https://user-images.githubusercontent.com/70617529/115147293-eef79280-a08c-11eb-9cb0-3ebb9bd495a8.png)

I managed to modify the code using nn.DataParallel to run on two GPUs with batch size 256, but the results are similar as above.  Another T-SNE plot is attached.
![image](https://user-images.githubusercontent.com/70617529/115147540-fd927980-a08d-11eb-85ee-ac59d70eb72e.png)

I really appreciate any help you can provide.

**Comment by divyat09** [comment]
Thanks, Ardor! Typically for batch size 256, you need 32 GB GPU memory. However, for smaller batch sizes like 128, the validation checks frequency for MatchDG Phase-I needs to be changed, and we should be able to achieve similar performance. I will work on it and make the results more easily reproducible with smaller batch sizes. 

Regarding MI attacks, the results need to be updated and I suggest you can follow this [paper](https://ppml-workshop.github.io/ppml20/pdfs/Mahajan_et_al.pdf) for results. I will soon update them in this repository. But your observations are consistent with Figure 1 of our [paper](https://ppml-workshop.github.io/ppml20/pdfs/Mahajan_et_al.pdf) on privacy, ERM gets between 65-70 percent MI attack accuracy (using classifier attack) and MatchDG is slightly higher.

Regarding the T-SNE plots, I am not sure and will take a look. However, I think match function metrics are better to evaluate the representation learnt. Did you observe any discrepancy using the match function metrics? You can find the exact commands to run in the [reproducing results notebook](https://github.com/microsoft/robustdg/blob/master/docs/notebooks/reproducing_results_matchdg_paper.ipynb). I have also mentioned them below for convenience:

python test.py --dataset rot_mnist --method_name matchdg_ctr --match_case 0.01 --match_flag 1 --pos_metric cos --test_metric match_score

**Comment by divyat09** [comment]
Hi Ardor, the code has been updated to follow the new results in our paper. The issues that you mentioned above should be resolved now.
